url: "https://coderic.org"
baseurl: "/FelixmarNavea/"
title: "Coderic"
network: "TEAM"
name: "Felixmar Navea"
description: "Sales Manager"
avatar_img_path: "imgs/felixmar-navea.jpg"
permalink: pretty
remote_theme: Coderic/coderic.org
